//
//  ConfigParser.swift
//  TCPConnection
//
//  Created by Rafael Krentz Gonçalves on 8/24/18.
//  Copyright © 2018 krentz. All rights reserved.
//

import Foundation

class ConfigParser {
    
    static let shared = ConfigParser()

    
    func parseConfig1(values: [CShort]){
        WifiDevice.shared.WIFI_HR_CS_SETTING_RESTORE_DEFAULT = Int(values[0])
        WifiDevice.shared.WIFI_HR_CS_SETTING_ACQUISITION_INTERVAL_LOG_S = Int(values[1])
        WifiDevice.shared.WIFI_HR_CS_ENABLE_REGISTER_LOG = Int(values[2])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_1 = Int(values[3])
        WifiDevice.shared.WIFI_HR_CS_SETTING_ACQUISITION_INTERVAL_SCAN_S = Int(values[4])
        WifiDevice.shared.WIFI_HR_CS_SETTING_START_MODE = Int(values[5])
        WifiDevice.shared.WIFI_HR_CS_SETTING_STOP_MODE = Int(values[6])
        WifiDevice.shared.WIFI_HR_CS_SETTING_ERASE_LOG_MEMORY = Int(values[7])
        WifiDevice.shared.WIFI_HR_CS_SETTING_CONFIGURATION_ONGOING = Int(values[8])
        WifiDevice.shared.WIFI_HR_CS_SETTING_YEAR_START_RECORD = Int(values[9])
        WifiDevice.shared.WIFI_HR_CS_SETTING_MONTH_START_RECORD = Int(values[10])
        WifiDevice.shared.WIFI_HR_CS_SETTING_DAY_START_RECORD = Int(values[11])
        WifiDevice.shared.WIFI_HR_CS_SETTING_HOUR_START_RECORD = Int(values[12])
        WifiDevice.shared.WIFI_HR_CS_SETTING_MINUTE_START_RECORD = Int(values[13])
        WifiDevice.shared.WIFI_HR_CS_SETTING_SECOND_START_RECORD = Int(values[14])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_5 = Int(values[15])
        WifiDevice.shared.WIFI_HR_CS_SETTING_YEAR_STOP_RECORD = Int(values[16])
        WifiDevice.shared.WIFI_HR_CS_SETTING_MONTH_STOP_RECORD = Int(values[17])
        WifiDevice.shared.WIFI_HR_CS_SETTING_DAY_STOP_RECORD = Int(values[18])
        WifiDevice.shared.WIFI_HR_CS_SETTING_HOUR_STOP_RECORD = Int(values[19])
        WifiDevice.shared.WIFI_HR_CS_SETTING_MINUTE_STOP_RECORD = Int(values[20])
        WifiDevice.shared.WIFI_HR_CS_SETTING_SECOND_STOP_RECORD = Int(values[21])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_6 = Int(values[22])
        WifiDevice.shared.WIFI_HR_CS_DISPLAY_ENABLE_MODE = Int(values[23])
        WifiDevice.shared.WIFI_HR_CS_DISPLAY_CONTRAST = Int(values[24])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_9 = Int(values[25])
        WifiDevice.shared.WIFI_HR_CS_BOOTLOADER_CONTROL = Int(values[26])
        WifiDevice.shared.WIFI_HR_CS_ALARM_BUZZER_DURATION_S = Int(values[27])
        WifiDevice.shared.WIFI_HR_CS_SETTING_DIGITAL_OUT_MODE = Int(values[28])
        WifiDevice.shared.WIFI_HR_CS_SETTING_DIGITAL_OUT_DURATION_S = Int(values[29])
        WifiDevice.shared.WIFI_HR_CS_MODBUS_ADDRESS = Int(values[30])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_14 = Int(values[31])
        WifiDevice.shared.WIFI_HR_CS_SETTING_TITLE_1 = Int(values[32])
        WifiDevice.shared.WIFI_HR_CS_SETTING_TITLE_2 = Int(values[33])
        WifiDevice.shared.WIFI_HR_CS_SETTING_TITLE_3 = Int(values[34])
        WifiDevice.shared.WIFI_HR_CS_SETTING_TITLE_4 = Int(values[35])
        WifiDevice.shared.WIFI_HR_CS_SETTING_TITLE_5 = Int(values[36])
        WifiDevice.shared.WIFI_HR_CS_SETTING_TITLE_6 = Int(values[37])
        WifiDevice.shared.WIFI_HR_CS_SETTING_TITLE_7 = Int(values[38])
        WifiDevice.shared.WIFI_HR_CS_SETTING_TITLE_8 = Int(values[39])
        WifiDevice.shared.WIFI_HR_CS_SETTING_TITLE_9 = Int(values[40])
        WifiDevice.shared.WIFI_HR_CS_SETTING_TITLE_10 = Int(values[41])
        WifiDevice.shared.WIFI_HR_CS_SETTING_PM = Int(values[42])
        WifiDevice.shared.WIFI_HR_CS_SETTING_GMT = Int(values[43])
        WifiDevice.shared.WIFI_HR_CS_SETTING_YEAR = Int(values[44])
        WifiDevice.shared.WIFI_HR_CS_SETTING_MONTH = Int(values[45])
        WifiDevice.shared.WIFI_HR_CS_SETTING_DAY = Int(values[46])
        WifiDevice.shared.WIFI_HR_CS_SETTING_HOUR = Int(values[47])
        WifiDevice.shared.WIFI_HR_CS_SETTING_MINUTE = Int(values[48])
        WifiDevice.shared.WIFI_HR_CS_SETTING_SECOND = Int(values[49])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_16 = Int(values[50])
        WifiDevice.shared.WIFI_HR_CS_BLE_ENABLED = Int(values[51])
        WifiDevice.shared.WIFI_HR_CS_BLE_ADVERTISE_MODE = Int(values[52])
        WifiDevice.shared.WIFI_HR_CS_BLE_ADVERTISE_TIME_ms = Int(values[53])
        WifiDevice.shared.WIFI_HR_CS_BLE_DEVICE_NAME_1 = Int(values[54])
        WifiDevice.shared.WIFI_HR_CS_BLE_DEVICE_NAME_2 = Int(values[55])
        WifiDevice.shared.WIFI_HR_CS_BLE_DEVICE_NAME_3 = Int(values[56])
        WifiDevice.shared.WIFI_HR_CS_BLE_DEVICE_NAME_4 = Int(values[57])
        WifiDevice.shared.WIFI_HR_CS_BLE_RESERVED_1 = Int(values[58])
        WifiDevice.shared.WIFI_HR_CS_BLE_RESERVED_2 = Int(values[59])
        WifiDevice.shared.WIFI_HR_CS_BLE_RESERVED_3 = Int(values[60])
        WifiDevice.shared.WIFI_HR_CS_BLE_FAST_ADVERTISE_DURATION_S = Int(values[61])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_18 = Int(values[62])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_19 = Int(values[63])
        WifiDevice.shared.WIFI_HR_CS_VBAT_VEXT_MIN_MAX_CLEAR_STATUS = Int(values[64])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_21 = Int(values[65])
        WifiDevice.shared.WIFI_HR_CS_15_4_ENABLED_RESERVED = Int(values[66])
        WifiDevice.shared.WIFI_HR_CS_15_4_ADVERTISE_MODE_RESERVED = Int(values[67])
        WifiDevice.shared.WIFI_HR_CS_15_4_ADVERTISE_TIME_RESERVED = Int(values[68])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_15_4_1 = Int(values[69])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_15_4_2 = Int(values[70])
        WifiDevice.shared.WIFI_HR_CS_15_4_PAN_ID_RESERVED = Int(values[71])
        WifiDevice.shared.WIFI_HR_CS_15_4_POWER_LEVEL_RESERVED = Int(values[72])
        WifiDevice.shared.WIFI_HR_CS_15_4_ENCRYPTION_ENABLED_RESERVED = Int(values[73])
        WifiDevice.shared.WIFI_HR_CS_15_4_ENCRYPTION_KEY_0_RESERVED = Int(values[74])
        WifiDevice.shared.WIFI_HR_CS_15_4_ENCRYPTION_KEY_1_RESERVED = Int(values[75])
        WifiDevice.shared.WIFI_HR_CS_15_4_ENCRYPTION_KEY_2_RESERVED = Int(values[76])
        WifiDevice.shared.WIFI_HR_CS_15_4_ENCRYPTION_KEY_3_RESERVED = Int(values[77])
        WifiDevice.shared.WIFI_HR_CS_15_4_ENCRYPTION_KEY_4_RESERVED = Int(values[78])
        WifiDevice.shared.WIFI_HR_CS_15_4_ENCRYPTION_KEY_5_RESERVED = Int(values[79])
        WifiDevice.shared.WIFI_HR_CS_15_4_ENCRYPTION_KEY_6_RESERVED = Int(values[80])
        WifiDevice.shared.WIFI_HR_CS_15_4_ENCRYPTION_KEY_7_RESERVED = Int(values[81])
        WifiDevice.shared.WIFI_HR_CS_CHD_DECIMAL_POINT = Int(values[82])
        WifiDevice.shared.WIFI_HR_CS_CHD_ALARM_MIN_HYSTERESIS = Int(values[83])
        WifiDevice.shared.WIFI_HR_CS_CHD_ALARM_MAX_HYSTERESIS = Int(values[84])
        WifiDevice.shared.WIFI_HR_CS_CHD_ALARM_MIN_MAX_CLEAR_STATUS = Int(values[85])
        WifiDevice.shared.WIFI_HR_CS_CHD_ENABLED = Int(values[86])
        WifiDevice.shared.WIFI_HR_CS_CHD_COUNTING_MODE = Int(values[87])
        WifiDevice.shared.WIFI_HR_CS_CHD_SENSOR_TYPE = Int(values[88])
        WifiDevice.shared.WIFI_HR_CS_CHD_COUNTING_EDGE = Int(values[89])
        WifiDevice.shared.WIFI_HR_CS_CHD_DEBOUNCE_TIME_ms = Int(values[90])
        WifiDevice.shared.WIFI_HR_CS_CHD_SENSOR_FACTOR_float_High = Int(values[91])
        WifiDevice.shared.WIFI_HR_CS_CHD_SENSOR_FACTOR_float_Low = Int(values[92])
        WifiDevice.shared.WIFI_HR_CS_CHD_SENSOR_UNIT = Int(values[93])
        WifiDevice.shared.WIFI_HR_CS_CHD_USER_SCALE_FACTOR_float_High = Int(values[94])
        WifiDevice.shared.WIFI_HR_CS_CHD_USER_SCALE_FACTOR_float_Low = Int(values[95])
        WifiDevice.shared.WIFI_HR_CS_CHD_USER_UNIT = Int(values[96])
        WifiDevice.shared.WIFI_HR_CS_CHD_ENABLE_ALARM_MIN = Int(values[97])
        WifiDevice.shared.WIFI_HR_CS_CHD_ENABLE_ALARM_MAX = Int(values[98])
        WifiDevice.shared.WIFI_HR_CS_CHD_ALARM_MIN = Int(values[99])
    }
    func parseConfig2(values: [CShort]){
        WifiDevice.shared.WIFI_HR_CS_CHD_ALARM_MAX = Int(values[0])
        WifiDevice.shared.WIFI_HR_CS_CHD_TAG_1 = Int(values[1])
        WifiDevice.shared.WIFI_HR_CS_CHD_TAG_2 = Int(values[2])
        WifiDevice.shared.WIFI_HR_CS_CHD_TAG_3 = Int(values[3])
        WifiDevice.shared.WIFI_HR_CS_CHD_TAG_4 = Int(values[4])
        WifiDevice.shared.WIFI_HR_CS_CHD_TAG_5 = Int(values[5])
        WifiDevice.shared.WIFI_HR_CS_CHD_TAG_6 = Int(values[6])
        WifiDevice.shared.WIFI_HR_CS_CHD_TAG_7 = Int(values[7])
        WifiDevice.shared.WIFI_HR_CS_CHD_TAG_8 = Int(values[8])
        WifiDevice.shared.WIFI_HR_CS_CHD_TAG_UNIT_1 = Int(values[9])
        WifiDevice.shared.WIFI_HR_CS_CHD_TAG_UNIT_2 = Int(values[10])
        WifiDevice.shared.WIFI_HR_CS_CHD_TAG_UNIT_3 = Int(values[11])
        WifiDevice.shared.WIFI_HR_CS_CHD_TAG_UNIT_4 = Int(values[12])
        WifiDevice.shared.WIFI_HR_CS_FREQUENCY_TO_FILTER = Int(values[13])
        WifiDevice.shared.WIFI_HR_CS_CH1_ENABLE = Int(values[14])
        WifiDevice.shared.WIFI_HR_CS_CH1_MODE = Int(values[15])
        WifiDevice.shared.WIFI_HR_CS_CH1_SENSOR_TYPE = Int(values[16])
        WifiDevice.shared.WIFI_HR_CS_CH1_UNIT = Int(values[17])
        WifiDevice.shared.WIFI_HR_CS_CH1_RANGE_MIN = Int(values[18])
        WifiDevice.shared.WIFI_HR_CS_CH1_RANGE_MAX = Int(values[19])
        WifiDevice.shared.WIFI_HR_CS_CH1_ENABLE_ALRM_MIN = Int(values[20])
        WifiDevice.shared.WIFI_HR_CS_CH1_ENABLE_ALRM_MAX = Int(values[21])
        WifiDevice.shared.WIFI_HR_CS_CH1_ALARM_MIN = Int(values[22])
        WifiDevice.shared.WIFI_HR_CS_CH1_ALARM_MAX = Int(values[23])
        WifiDevice.shared.WIFI_HR_CS_CH1_DECIMAL_POINT = Int(values[24])
        WifiDevice.shared.WIFI_HR_CS_CH1_GAIN_USER_RESERVED = Int(values[25])
        WifiDevice.shared.WIFI_HR_CS_CH1_OFFSET_USER = Int(values[26])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_28 = Int(values[27])
        WifiDevice.shared.WIFI_HR_CS_CH1_TAG_1 = Int(values[28])
        WifiDevice.shared.WIFI_HR_CS_CH1_TAG_2 = Int(values[29])
        WifiDevice.shared.WIFI_HR_CS_CH1_TAG_3 = Int(values[30])
        WifiDevice.shared.WIFI_HR_CS_CH1_TAG_4 = Int(values[31])
        WifiDevice.shared.WIFI_HR_CS_CH1_TAG_5 = Int(values[32])
        WifiDevice.shared.WIFI_HR_CS_CH1_TAG_6 = Int(values[33])
        WifiDevice.shared.WIFI_HR_CS_CH1_TAG_7 = Int(values[34])
        WifiDevice.shared.WIFI_HR_CS_CH1_TAG_8 = Int(values[35])
        WifiDevice.shared.WIFI_HR_CS_CH1_TAG_UNIT_1 = Int(values[36])
        WifiDevice.shared.WIFI_HR_CS_CH1_TAG_UNIT_2 = Int(values[37])
        WifiDevice.shared.WIFI_HR_CS_CH1_TAG_UNIT_3 = Int(values[38])
        WifiDevice.shared.WIFI_HR_CS_CH1_TAG_UNIT_4 = Int(values[39])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_29 = Int(values[40])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_NUM_OF_POINTS = Int(values[41])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_LOGBOX_1 = Int(values[42])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_LOGBOX_2 = Int(values[43])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_LOGBOX_3 = Int(values[44])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_LOGBOX_4 = Int(values[45])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_LOGBOX_5 = Int(values[46])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_LOGBOX_6 = Int(values[47])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_LOGBOX_7 = Int(values[48])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_LOGBOX_8 = Int(values[49])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_LOGBOX_9 = Int(values[50])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_LOGBOX_10 = Int(values[51])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_PADRAO_1 = Int(values[52])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_PADRAO_2 = Int(values[53])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_PADRAO_3 = Int(values[54])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_PADRAO_4 = Int(values[55])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_PADRAO_5 = Int(values[56])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_PADRAO_6 = Int(values[57])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_PADRAO_7 = Int(values[58])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_PADRAO_8 = Int(values[59])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_PADRAO_9 = Int(values[60])
        WifiDevice.shared.WIFI_HR_CS_CH1_CUSTOM_CALIB_PADRAO_10 = Int(values[61])
        WifiDevice.shared.WIFI_HR_CS_CH1_ALARM_MIN_HYSTERESIS = Int(values[62])
        WifiDevice.shared.WIFI_HR_CS_CH1_ALARM_MAX_HYSTERESIS = Int(values[63])
        WifiDevice.shared.WIFI_HR_CS_CH1_ALARM_MIN_MAX_CLEAR_STATUS = Int(values[64])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_33 = Int(values[65])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_34 = Int(values[66])
        WifiDevice.shared.WIFI_HR_CS_CH2_ENABLE = Int(values[67])
        WifiDevice.shared.WIFI_HR_CS_CH2_MODE = Int(values[68])
        WifiDevice.shared.WIFI_HR_CS_CH2_SENSOR_TYPE = Int(values[69])
        WifiDevice.shared.WIFI_HR_CS_CH2_UNIT = Int(values[70])
        WifiDevice.shared.WIFI_HR_CS_CH2_RANGE_MIN = Int(values[71])
        WifiDevice.shared.WIFI_HR_CS_CH2_RANGE_MAX = Int(values[72])
        WifiDevice.shared.WIFI_HR_CS_CH2_ENABLE_ALRM_MIN = Int(values[73])
        WifiDevice.shared.WIFI_HR_CS_CH2_ENABLE_ALRM_MAX = Int(values[74])
        WifiDevice.shared.WIFI_HR_CS_CH2_ALARM_MIN = Int(values[75])
        WifiDevice.shared.WIFI_HR_CS_CH2_ALARM_MAX = Int(values[76])
        WifiDevice.shared.WIFI_HR_CS_CH2_DECIMAL_POINT = Int(values[77])
        WifiDevice.shared.WIFI_HR_CS_CH2_GAIN_USER_RESERVED = Int(values[78])
        WifiDevice.shared.WIFI_HR_CS_CH2_OFFSET_USER = Int(values[79])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_36 = Int(values[80])
        WifiDevice.shared.WIFI_HR_CS_CH2_TAG_1 = Int(values[81])
        WifiDevice.shared.WIFI_HR_CS_CH2_TAG_2 = Int(values[82])
        WifiDevice.shared.WIFI_HR_CS_CH2_TAG_3 = Int(values[83])
        WifiDevice.shared.WIFI_HR_CS_CH2_TAG_4 = Int(values[84])
        WifiDevice.shared.WIFI_HR_CS_CH2_TAG_5 = Int(values[85])
        WifiDevice.shared.WIFI_HR_CS_CH2_TAG_6 = Int(values[86])
        WifiDevice.shared.WIFI_HR_CS_CH2_TAG_7 = Int(values[87])
        WifiDevice.shared.WIFI_HR_CS_CH2_TAG_8 = Int(values[88])
        WifiDevice.shared.WIFI_HR_CS_CH2_TAG_UNIT_1 = Int(values[89])
        WifiDevice.shared.WIFI_HR_CS_CH2_TAG_UNIT_2 = Int(values[90])
        WifiDevice.shared.WIFI_HR_CS_CH2_TAG_UNIT_3 = Int(values[91])
        WifiDevice.shared.WIFI_HR_CS_CH2_TAG_UNIT_4 = Int(values[92])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_37 = Int(values[93])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_NUM_OF_POINTS = Int(values[94])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_LOGBOX_1 = Int(values[95])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_LOGBOX_2 = Int(values[96])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_LOGBOX_3 = Int(values[97])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_LOGBOX_4 = Int(values[98])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_LOGBOX_5 = Int(values[99])
    }
    func parseConfig3(values: [CShort]){
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_LOGBOX_6 = Int(values[0])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_LOGBOX_7 = Int(values[1])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_LOGBOX_8 = Int(values[2])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_LOGBOX_9 = Int(values[3])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_LOGBOX_10 = Int(values[4])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_PADRAO_1 = Int(values[5])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_PADRAO_2 = Int(values[6])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_PADRAO_3 = Int(values[7])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_PADRAO_4 = Int(values[8])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_PADRAO_5 = Int(values[9])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_PADRAO_6 = Int(values[10])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_PADRAO_7 = Int(values[11])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_PADRAO_8 = Int(values[12])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_PADRAO_9 = Int(values[13])
        WifiDevice.shared.WIFI_HR_CS_CH2_CUSTOM_CALIB_PADRAO_10 = Int(values[14])
        WifiDevice.shared.WIFI_HR_CS_CH2_ALARM_MIN_HYSTERESIS = Int(values[15])
        WifiDevice.shared.WIFI_HR_CS_CH2_ALARM_MAX_HYSTERESIS = Int(values[16])
        WifiDevice.shared.WIFI_HR_CS_CH2_ALARM_MIN_MAX_CLEAR_STATUS = Int(values[17])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_41 = Int(values[18])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_42 = Int(values[19])
        WifiDevice.shared.WIFI_HR_CS_CH3_ENABLE = Int(values[20])
        WifiDevice.shared.WIFI_HR_CS_CH3_MODE = Int(values[21])
        WifiDevice.shared.WIFI_HR_CS_CH3_SENSOR_TYPE = Int(values[22])
        WifiDevice.shared.WIFI_HR_CS_CH3_UNIT = Int(values[23])
        WifiDevice.shared.WIFI_HR_CS_CH3_RANGE_MIN = Int(values[24])
        WifiDevice.shared.WIFI_HR_CS_CH3_RANGE_MAX = Int(values[25])
        WifiDevice.shared.WIFI_HR_CS_CH3_ENABLE_ALRM_MIN = Int(values[26])
        WifiDevice.shared.WIFI_HR_CS_CH3_ENABLE_ALRM_MAX = Int(values[27])
        WifiDevice.shared.WIFI_HR_CS_CH3_ALARM_MIN = Int(values[28])
        WifiDevice.shared.WIFI_HR_CS_CH3_ALARM_MAX = Int(values[29])
        WifiDevice.shared.WIFI_HR_CS_CH3_DECIMAL_POINT = Int(values[30])
        WifiDevice.shared.WIFI_HR_CS_CH3_GAIN_USER_RESERVED = Int(values[31])
        WifiDevice.shared.WIFI_HR_CS_CH3_OFFSET_USER = Int(values[32])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_44 = Int(values[33])
        WifiDevice.shared.WIFI_HR_CS_CH3_TAG_1 = Int(values[34])
        WifiDevice.shared.WIFI_HR_CS_CH3_TAG_2 = Int(values[35])
        WifiDevice.shared.WIFI_HR_CS_CH3_TAG_3 = Int(values[36])
        WifiDevice.shared.WIFI_HR_CS_CH3_TAG_4 = Int(values[37])
        WifiDevice.shared.WIFI_HR_CS_CH3_TAG_5 = Int(values[38])
        WifiDevice.shared.WIFI_HR_CS_CH3_TAG_6 = Int(values[39])
        WifiDevice.shared.WIFI_HR_CS_CH3_TAG_7 = Int(values[40])
        WifiDevice.shared.WIFI_HR_CS_CH3_TAG_8 = Int(values[41])
        WifiDevice.shared.WIFI_HR_CS_CH3_TAG_UNIT_1 = Int(values[42])
        WifiDevice.shared.WIFI_HR_CS_CH3_TAG_UNIT_2 = Int(values[43])
        WifiDevice.shared.WIFI_HR_CS_CH3_TAG_UNIT_3 = Int(values[44])
        WifiDevice.shared.WIFI_HR_CS_CH3_TAG_UNIT_4 = Int(values[45])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_45 = Int(values[46])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_NUM_OF_POINTS = Int(values[47])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_LOGBOX_1 = Int(values[48])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_LOGBOX_2 = Int(values[49])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_LOGBOX_3 = Int(values[50])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_LOGBOX_4 = Int(values[51])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_LOGBOX_5 = Int(values[52])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_LOGBOX_6 = Int(values[53])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_LOGBOX_7 = Int(values[54])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_LOGBOX_8 = Int(values[55])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_LOGBOX_9 = Int(values[56])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_LOGBOX_10 = Int(values[57])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_PADRAO_1 = Int(values[58])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_PADRAO_2 = Int(values[59])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_PADRAO_3 = Int(values[60])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_PADRAO_4 = Int(values[61])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_PADRAO_5 = Int(values[62])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_PADRAO_6 = Int(values[63])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_PADRAO_7 = Int(values[64])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_PADRAO_8 = Int(values[65])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_PADRAO_9 = Int(values[66])
        WifiDevice.shared.WIFI_HR_CS_CH3_CUSTOM_CALIB_PADRAO_10 = Int(values[67])
        WifiDevice.shared.WIFI_HR_CS_CH3_ALARM_MIN_HYSTERESIS = Int(values[68])
        WifiDevice.shared.WIFI_HR_CS_CH3_ALARM_MAX_HYSTERESIS = Int(values[69])
        WifiDevice.shared.WIFI_HR_CS_CH3_ALARM_MIN_MAX_CLEAR_STATUS = Int(values[70])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_49 = Int(values[71])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_50 = Int(values[72])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_51 = Int(values[73])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_52 = Int(values[74])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_53 = Int(values[75])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_54 = Int(values[76])
        WifiDevice.shared.WIFI_HR_CS_RESERVED_55 = Int(values[77])
        WifiDevice.shared.WIFI_HR_CS_WIFI_ENABLE = Int(values[78])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_0_1 = Int(values[79])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_2_3 = Int(values[80])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_4_5 = Int(values[81])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_6_7 = Int(values[82])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_8_9 = Int(values[83])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_10_11 = Int(values[84])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_12_13 = Int(values[85])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_14_15 = Int(values[86])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_16_17 = Int(values[87])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_18_19 = Int(values[88])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_20_21 = Int(values[89])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_22_23 = Int(values[90])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_24_25 = Int(values[91])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_26_27 = Int(values[92])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_28_29 = Int(values[93])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_30_31 = Int(values[94])
        WifiDevice.shared.WIFI_HR_CS_WIFI_SSID_32_33 = Int(values[95])
        WifiDevice.shared.WIFI_HR_CS_WIFI_PASS_0_1 = Int(values[96])
        WifiDevice.shared.WIFI_HR_CS_WIFI_PASS_2_3 = Int(values[97])
        WifiDevice.shared.WIFI_HR_CS_WIFI_PASS_4_5 = Int(values[98])
        WifiDevice.shared.WIFI_HR_CS_WIFI_PASS_6_7 = Int(values[99])
    }
    func parseConfig4(values: [CShort]){
        
    }
    func parseConfig5(values: [CShort]){
        
    }
    func parseConfig6(values: [CShort]){
        
    }
    func parseConfig7(values: [CShort]){
        
    }
    func parseConfig8(values: [CShort]){
        
    }
    func parseConfig9(values: [CShort]){
        
    }
    func parseConfig10(values: [CShort]){
        
    }
    func parseConfig11(values: [CShort]){
        
    }
}
